language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
 - docker run -v /tmp/green:/green/bin green /bin/sh -c "ant;ant test"
 - grep /tmp/green/junit/TEST-za.ac.sun.cs.green.EntireSuite.txt AssertionFailedError
