language: java

services:
  - docker

before_install:
  - docker build -t green .

script:
 - docker run -v /tmp/green:/green/bin green /bin/sh -c "ant;ant test"
 #- docker run -it green /bin/sh -c "pwd"
 - ls /tmp/green
